
import java.util.List;
import org.hibernate.Session;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class GUIAdministrarVariedad extends javax.swing.JFrame {
    private GUIPizzeriaCantidades pizzeria;
    /**
     * Creates new form GUIAdministrarVariedad
     */
    public GUIAdministrarVariedad() {
        initComponents();
        iniciar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelSelectVariedad = new javax.swing.JLabel();
        comboBoxDeVariedad = new javax.swing.JComboBox<>();
        leerNuevoPrecio = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        botonFinalizar = new javax.swing.JButton();
        labelErrorNuevoPrecio = new javax.swing.JLabel();
        botonEliminarVariedad = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelSelectVariedad.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        labelSelectVariedad.setText("Variedad:");

        comboBoxDeVariedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxDeVariedadActionPerformed(evt);
            }
        });

        leerNuevoPrecio.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Nuevo Precio:");

        botonFinalizar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        botonFinalizar.setText("Listo");
        botonFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFinalizarActionPerformed(evt);
            }
        });

        labelErrorNuevoPrecio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelErrorNuevoPrecio.setForeground(new java.awt.Color(255, 51, 51));

        botonEliminarVariedad.setLabel("Eliminar la variedad");
        botonEliminarVariedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarVariedadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelSelectVariedad)
                    .addComponent(jLabel1))
                .addGap(115, 115, 115)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(leerNuevoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxDeVariedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelErrorNuevoPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(botonEliminarVariedad)
                        .addGap(0, 61, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(botonFinalizar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSelectVariedad)
                    .addComponent(comboBoxDeVariedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonEliminarVariedad))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(leerNuevoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(labelErrorNuevoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addComponent(botonFinalizar)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFinalizarActionPerformed
        AdministradorDeVariedades admin=new AdministradorDeVariedades();
        int indice=comboBoxDeVariedad.getSelectedIndex();
        try{
            Float precio=Float.valueOf(leerNuevoPrecio.getText());
            Variedad variedad=admin.obtenerVariedades().get(indice);
            Session session= NewHibernateUtil.getSessionFactory().openSession();
            session.beginTransaction();
            variedad.setPrecio(precio);
            session.merge(variedad);
            session.getTransaction().commit();
            session.close();
            this.setVisible(false);
            
        }catch(Exception e){
            System.out.println(e.getMessage());
            labelErrorNuevoPrecio.setText("Precio Invalido");
        }
    }//GEN-LAST:event_botonFinalizarActionPerformed

    private void comboBoxDeVariedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxDeVariedadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxDeVariedadActionPerformed

    private void botonEliminarVariedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarVariedadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonEliminarVariedadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIAdministrarVariedad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIAdministrarVariedad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIAdministrarVariedad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIAdministrarVariedad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIAdministrarVariedad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEliminarVariedad;
    private javax.swing.JButton botonFinalizar;
    private javax.swing.JComboBox<String> comboBoxDeVariedad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelErrorNuevoPrecio;
    private javax.swing.JLabel labelSelectVariedad;
    private javax.swing.JTextField leerNuevoPrecio;
    // End of variables declaration//GEN-END:variables

    private void iniciar() {
        AdministradorDeVariedades admin= new AdministradorDeVariedades();
        List<Variedad> variedades=admin.obtenerVariedades();
        for(Variedad v:variedades){
            
            comboBoxDeVariedad.addItem(v.getNombrePizza());
        }
         
    }

    public void setPizzeria(GUIPizzeriaCantidades pizzeria) {
        this.pizzeria = pizzeria;
    }
    
}
